name: Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC 필수
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (필요 시 빌드 단계 추가, 예: npm run build)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::086015456585:role/GitHubActionsDeployRole
          aws-region: ap-northeast-2  # 예: ap-northeast-2

      - name: Sync to S3
        run: aws s3 sync ./web/ s3://www.edumgt.co.kr
